### PR TITLE
Spell mistake in friendshipAccept() method

### PR DESCRIPTION
**Pull request by su-chang**

### CODE REVIEW

**Comment by su-chang** [comment]
Related issue: https://github.com/wechaty/wechaty-puppet-hostie/issues/33

Maybe we should fix something in `@chatie/grpc` first.

**Comment by huan** [comment]
Good catch!

Could you please also send a pull request to the grpc module?

Thank you very much!

**Comment by huan** [comment]
Please update this PR because the @chatie/grpc has been upgraded to 0.15 with your PR.

**Comment by su-chang** [comment]
Hmmm, does this PR could resolve #33 ? This problem make donut can not get friendshipAccept() request by some reason which I'm not clear.

**Comment by huan** [comment]
I'm not sure about that, still have a look at it later.

**Pull request merged**
